### ISSUE TITLE
Přesun jednoho api endpointu.

### ISSUE THREAD

**Issue by Kaacz** [waladir/plugin.video.archivo2tv#4]
Koukám do zdroje a bylo by dobré udělat změny.
- www.o2tv.cz se rozhodilo na main endpoint a podpůrné endpointy (api.o2tv.cz apod). Bylo by dobré to upravit než na hlavním endpointu zmizí. dtto assets a img1.
- https://ottmediator.o2tv.cz:4443/ottmediator-war/* změnit na https://ottmediator.o2tv.cz:443/ottmediator-war/*

Proč Github zrušil možnost zprávy... :(

**Comment by Kaacz** [comment]
https://ottmediator.o2tv.cz:4443/ottmediator-war/* změnit na https://ottmediator.o2tv.cz:443/ottmediator-war/*

**Comment by waladir** [comment]
Díky za upozornění. Ve verzi 2.1.9 jsou URL endointů upravené.
