### ISSUE TITLE
Černá obrazovka při zapnutí kanálů

### ISSUE THREAD

**Issue by VlastikYoutubeKo** [waladir/plugin.video.archivo2tv#7]
Mám problém.
Mám KODI 19.1 Matrix, vše funguje normálně, jenom problém je, že mám černou obrazovku ale se zvukem. Log doložím až budu mít.

EDIT: https://paste.kodi.tv/ibazocuney

**Comment by waladir** [comment]
Pošli prosím log se zapnutým debugem:
- v nastavení Kodi - Systém - Protokolování povol Povolit protokolování ladění
- v doplňku na záložce Logování zapni volby Logovaní požadavků a Logování odpovědí

Nejsem si jistý jestli s tím něco půjde udělat, protože doplněk jen získá URL streamu a ten přehrává Kodi. Osobně tipuju, že to bude mít souvislost s historickým HW. Můžeš ještě zkusit změnit v Nastavení - Přehrávač - Video nastavení Povolit hardwarovou akceleraci - DXVA2. U SW dekodování by ale mohl mít procesor problémy.

**Comment by VlastikYoutubeKo** [comment]
Dobře, zkusím!

**Comment by VlastikYoutubeKo** [comment]
> Nejsem si jistý jestli s tím něco půjde udělat, protože doplněk jen získá URL streamu a ten přehrává Kodi. Osobně tipuju, že to bude mít souvislost s historickým HW. Můžeš ještě zkusit změnit v Nastavení - Přehrávač - Video nastavení Povolit hardwarovou akceleraci - DXVA2. U SW dekodování by ale mohl mít procesor problémy.

Zkusil jsem to vypnout, a funguje to :D
Vyřešeno
