### ISSUE TITLE
O2TV Sport

### ISSUE THREAD

**Issue by camel1cz** [waladir/plugin.video.archivo2tv#9]
Ahoj,

úvodem děkuji za pěknou práci - vše funguje jak má! Díky!

Mám ale přeci jen jeden problém - v seznamu kanálů nevidím O2TV Sport (kvůli kterému ostatně mám O2TV koupenou) - čím to je?
Všiml jsem si, že v enigma2 mi plugin také přestal sportovní kanály O2TV nabízet...

Dělám něco blbě nebo čím to je?

Moc díky!

**Comment by waladir** [comment]
Pravděpodobně souvisí s účty/službami u O2TV.
